# Init #
project: 'egnn-model'
job_type: 'train'
# load_id: '11y81hfn'

# Data #
data_fields: 'wst'
train_cases: [700,900,1100,1300]
test_case: 1000
num_nodes: -1
tspan: [25,75]
rollout: 1
rkm: [[.05,0,8], [.2,0,8], [.5,0,8]]

# Model #
num_levels: 3
cf: [8, 8]
skip_mp_levels_all: [[0,1],[0,2],[0,2],[1,2],[1,2],[1,2]]
latent_layers: 6
latent_dim: 64
latent_vectors: False
model_type: 'equivariant'
act: 'silu'
solver: 'euler'
sensitivity: 'autograd'

# Training #
data_aug: False
batch_size: 2
lr: 0.0003
lr_sch: True
epochs: 5000
gpus: -1
noise_fac: 2.