# Init #
project: 'egnn-model'
job_type: 'train'
# load_id: '2o6lwils'

# Data #
data_fields: 'wst'
train_cases: [700,900,1100,1300]
test_case: 1000
num_nodes: -1
tspan: [0,50]
rollout: 1
# test_rollout: 0
rkm: [[.05,0,[8,32]], [.2,0,[8,32]], [.5,0,[8,32]]]

# Model #
num_levels: 3
cf: [8, 8]
skip_mp_levels_all: [[0,1],[0,2],[0,2],[1,2],[1,2],[1,2]]
latent_layers: 6
latent_dim: 256
latent_vectors: False
model_type: 'equivariant'
act: 'silu'
solver: 'euler'
sensitivity: 'autograd'

# Training #
data_aug: False
batch_size: 2
lr: 0.00005
lr_sch: True
noise_fac: 0.001
noise_sch: True
epochs: 5000
gpus: -1